# Funding options for MCP Dockerize

github: # Add your GitHub username when ready
# patreon: # Add your Patreon username when ready
# open_collective: # Add your Open Collective username when ready
# ko_fi: # Add your Ko-fi username when ready
# custom: # Add custom funding URL when ready
